pipeline {
  agent any

  options {
    timestamps()
    
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Lint') {
      steps {
        sh '''
          echo "=== Lint stage ==="
          make lint
        '''
      }
    }

    stage('Test') {
      steps {
        sh '''
          echo "=== Test stage ==="
          make test
        '''
      }
    }

    stage('Publish artifacts') {
      steps {
        sh '''
          echo "=== Publish artifacts stage ==="
          mkdir -p logs
          echo "Build number: ${BUILD_NUMBER}, > logs/build-info-ci2.txt
        '''
        archiveArtifacts artifacts: 'logs/**', allowEmptyArchive: true
      }
    }
  }

  post {
    always {
      echo "Cleaning workspace..."
      cleanWs()
    }
  }
}
